# Executive Summary

Include a first paragraph executive summary.

Context

You work for Motor Trend, a magazine about the automobile industry. Looking at a data set of a collection of cars, they are interested in exploring the relationship between a set of variables and miles per gallon (MPG) (outcome). They are particularly interested in the following two questions:

***"Is an automatic or manual transmission better for MPG"***

***"Quantify the MPG difference between automatic and manual transmissions"***

*	"Data supports the claim that if Kobe stops ball hogging the Lakers will win more"
*	"Linear regression suggests that an increase of 1% in % of shots taken by Kobe results in a drop of 1.16 points (+/- 0.22) in score differential."


## Question

Take the mtcars data set and write up an analysis to answer their question using regression models and exploratory data analyses.

Your report must be:

* Written as a PDF printout of a compiled (using knitr) R markdown document.
* Brief. Roughly the equivalent of 2 pages or less for the main text. Supporting figures in an appendix can be included up to 5 total pages including the 2 for the main report. The appendix can only include figures.

Peer Grading

* Did the student interpret the coefficients correctly?
* Did the student do some exploratory data analyses?
* Did the student fit multiple models and detail their strategy for model selection?
* Did the student answer the questions of interest or detail why the question(s) is (are) not answerable?
* Did the student do a residual plot and some diagnostics?
* Did the student quantify the uncertainty in their conclusions and/or perform an inference correctly?
* Was the report brief (about 2 pages long) for the main body of the report and no longer than 5 with supporting appendix of figures?
* Did the report include an executive summary?
* Was the report done in Rmd (knitr)?
